-- AlterTable
ALTER TABLE "User" ADD COLUMN "canLog" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canIssues" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canHours" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canTodos" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canCalendar" BOOLEAN NOT NULL DEFAULT true;
